# -*- mode: ruby -*-
# vi: set ft=ruby :

RAM = 1024
CPU = 1

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "10.0.0.10"
  config.vm.provision "ansible_local" do |ans|
    ans.playbook = "nginx.yaml"
    ans.install = true
    ans.install_mode = "pip"
    ans.pip_install_cmd = "curl https://boostrap.pypa.io/pip/3.5/get-pip.py | sudo python"
  end
  config.vm.provider "virtualbox" do |v|
    v.memory = RAM
    v.cpus = CPU
  end
end

