# -*- mode: ruby -*-
# vi: set ft=ruby :
NAME = "ubuntu/trusty64"
CPU = 2
RAM = 2048
IP = "10.0.0.10"


Vagrant.configure("2") do |config|
  config.vm.box = NAME
  config.vm.network "private_network", ip: IP
  config.vm.provider "virtualbox" do |v|
    v.memory = RAM
    v.cpus = CPU
  end
end


