# -*- mode: ruby -*-
# vi: set ft=ruby :
RAM = 1024
CPU = 1
IP = "10.0.0.10" 
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = "lb"
    config.vm.network "private_network", ip: IP
    config.vm.synced_folder "static-website-example/", "/var/www/html"
    config.vm.provider "virtualbox" do |v|
      v.memory = RAM
      v.cpus = CPU
  end
end